### ISSUE TITLE
Update "About" screen to remove R from PhET

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/brand#35]
The PhET says ® on it in the 'About' screen. We still want to indicate that this is our trademark so change that line to read ... 

PhET™ Interactive Simulations

I also reviewed the link to Terms, Privacy, and Licensing, and while that says we are a registered trademark, I think it is fine. We are registered, and people should know that. The main issue is that our sims our used in so many places we don't want the R symbol to be viewed as a marketing piece in these countries, and violate local laws. This webpage lives on our website, served from our country.

**Comment by samreid** [comment]
I pushed a proposed fix.  In context it looks like this:

![image](https://user-images.githubusercontent.com/679486/53359617-9c791c00-38f0-11e9-94f6-45fb4a05a9b1.png)

The previous unicode for (R) was also embedded in a `<sup>` superscript.  I also tried that for the TM but it made it very high and tiny:

![image](https://user-images.githubusercontent.com/679486/53359650-bd417180-38f0-11e9-866e-b6ba96e391ab.png)

So I've committed without the `<sup>` since it looks like the TM is already rendered kind of like a superscript.

Leaving assigned to @ariel-phet and reassigning to @kathy-phet for review and feedback.  You can see it live on phettest.

**Comment by kathy-phet** [comment]
I think I prefer the non-sup version, but could go either way. @ariel-phet - do you have a preference here?

**Comment by ariel-phet** [comment]
non-sup is the way to go @samreid
